export const projects = [
  {
    id: 1,
    title: "CortechsLab.ma laboratory fourniseur ",
    p_description: "website about the laboratory machines",
    image: "/projects/cortechslab maroc.png",
    tags: ["WordPress", "WooCommerce", "SEO", "PHP", "mailing", "cloudFlare "],
    demoUrl: "https://cortechslab.ma/",
    github_repo: "",
  },
  {
    id: 2,
    title: "My Movies library ",
    p_description:
      "fully interactif movies library livetime movies search movies favoris ",
    image: "/projects/My  movies library.png",
    tags: ["HTML", "CSS", "Java Script", "Local Storage"],
    demoUrl: "",
    github_repo: "https://github.com/ISMOUSLIH/My-movies-Library",
  },
  {
    id: 3,
    title: "Go To Gether",
    p_description: "Car polling webapp fully interactions map and rides ",
    image: "/projects/Gotogether.png",
    tags: [
      "NODE.JS",
      "EXPRESS.JS",
      "REACT.JS",
      "MONGO DB",
      "HTML",
      "CSS",
      "tailwind",
      "Java Script",
    ],
    demoUrl: "",
    // github_repo: "https://github.com/ISMOUSLIH/My-movies-Library",
  },
  {
    id: 4,
    title: "iPhs | By Alphastra",
    p_description: "IPHA is an innovative healthcare application",
    image: "/projects/iPha by alphastra.png",
    tags: [
      "NODE.JS",
      "Next.JS",
      "REACT.JS",
      "MONGO DB",
      "AWS S3",
      "Docker",
      "tailwind",
      "Java Script",
    ],
    demoUrl: "https://alphastra.com/ipha/index.html",
    // github_repo: "https://github.com/ISMOUSLIH/My-movies-Library",
  },

  // {
  //   id: 4,
  //   title: "Jumia Order Tracker",
  //   p_description: "",
  //   image: "/projects/cortechslab maroc.png",
  //   tags: ["Laravel", "MySql"],
  //   demoUrl: null,
  //   github_repo: null,
  // },
];
